name: kshethra_mini
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  build_runner: ^2.4.15
  qr_flutter: ^4.1.0
  lottie: ^3.3.1
  image_picker: ^1.1.2
  permission_handler: ^12.0.0+1
  easy_localization: ^3.0.7+1
  translator: ^1.0.3+1
  hive: ^2.2.3
  shared_preferences: ^2.5.3
  path_provider: ^2.1.5
  shimmer: ^3.0.0
  flutter_secure_storage: ^9.2.4
  dio: ^5.8.0+1
  intl: ^0.20.2
  jwt_decoder: ^2.0.1
  device_info_plus: ^11.5.0
  video_player: ^2.10.0
#  file_picker: ^10.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_gen_runner: any
  flutter_launcher_icons: ^0.14.4

flutter_gen:
  output: lib\utils\asset
  line_length: 80

flutter_icons:
  android: true
  ios: true
  image_path_ios: "assets/icons/app_icon.png"
  adaptive_icon_background: "#000000"
  adaptive_icon_foreground: "assets/icons/app_icon.png"
  image_path_android: "assets/icons/app_icon.png"
  remove_alpha_ios: true


flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/gifs/
    - assets/translations/
    - assets/videos/

  fonts:
    - family: poppins
      fonts:
        - asset: assets/fonts/Poppins-Bold.ttf
        - asset: assets/fonts/Poppins-Light.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-SemiBold.ttf
